In [1]:
import json
import os
import jieba
from dataset import PairDataset

In [2]:
data = PairDataset(filename='../files/train.txt')
vocab = data.bulid_vocab()

Reading dataset ../files/train.txt... 43995 paris.


In [4]:
# 测试SimpleDataset
from dataset import SimpleDataset
df = SimpleDataset(data.pairs, vocab)
for m in df:
    print(m)
    break

{'x': [1, 2717, 2718, 2719, 2720, 2721, 2722, 241, 2723, 2724, 2725, 2726, 2727, 126, 2728, 2729, 0, 2730, 0, 2731, 2732, 0, 2733, 0, 2734, 0, 2735, 2736, 0, 2737, 2736, 0, 2738, 116, 0, 2739, 0, 2740, 0, 2741, 2720, 0, 2742, 133, 2743, 0, 2744, 0, 2734, 2745, 0, 2746, 2, 0, 2747, 2748, 0, 2749, 2, 0, 2750, 2751, 1, 2752, 0, 2753, 2745, 0, 2754, 2755, 1, 2756, 2757, 2758, 0, 2741, 2720, 2750, 2751, 1, 2752, 0, 2759, 0, 2731, 2760, 0, 2761, 0, 2762, 0, 2763, 0, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2], 'OOV': ['雪中飞', '春夏', '新款', '柔软', '舒适', '百搭高', '纯色', '针织', '不规则', '半身裙', '运动', '黑色商品', '卖点', '裤长', '面料', '特色', '浅麻灰', '下摆', '细节', '展示', '模特', '商品', '腰围', '胸围', '手感', '耐穿', '打理', '黑色', '设计', '弹性', '浅麻', '灰黑色', '透明', '具有', '良好', '透气性', '腰部', '打造', '自然', 'causal', '通勤', '造型', '适中', '解析', '不透', '背面', '正面', '微弹弹力', '高弹力流行元素', '不规则图案', '纯色适用年龄', '25-29周岁品牌', '雪中飞（SNOW', 'FLYING）材质', '其它腰型', '高腰上市时间', '2019年春季厚度', '常规廓形', 'H型裙长', '中裙裙型', '不规则风格'

In [5]:
import torch.nn as nn
import torch
em = nn.Embedding(300,100)

# bs, seq_len, hidden_size
em(torch.tensor([[1, 2,3], [4, 5, 6], [7, 8, 9]])).shape

torch.Size([3, 3, 100])

In [10]:
x = torch.rand(3, 2)
torch.sum(x, dim=0, keepdim=True).shape

torch.Size([1, 2])

In [13]:
torch.ne(torch.arange(10), 1).byte()

tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.uint8)

In [15]:
t = torch.tensor([[1, 2], [3, 4]])
print(t)
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 4]])


tensor([[1, 1],
        [4, 3]])

In [25]:
a = torch.arange(5)
b = torch.tensor([0, 0, 4, 5, 6])
print(a, b)
torch.min(a, b)

tensor([0, 1, 2, 3, 4]) tensor([0, 0, 4, 5, 6])


tensor([0, 0, 2, 3, 4])

In [1]:
import time
from tqdm import tqdm

with tqdm(total=200) as pbar:
    for i in range(20):
        pbar.update(10)
        time.sleep(.1)

100%|██████████| 200/200 [00:02<00:00, 91.24it/s]


In [4]:
import pickle
tup1 = ('I love Python', {1,2,3}, None)

p1 = pickle.dumps(tup1)
print(p1)

t2 = pickle.loads(p1)
print(t2)

b'\x80\x04\x95\x1e\x00\x00\x00\x00\x00\x00\x00\x8c\rI love Python\x94\x8f\x94(K\x01K\x02K\x03\x90N\x87\x94.'
('I love Python', {1, 2, 3}, None)


pickle.dump()函数

In [6]:
import pickle
tup1 = ('I love Python', {1,2,3}, None)
#使用 dumps() 函数将 tup1 转成 p1
with open ("a.pickle", 'wb') as f: #打开文件
    pickle.dump(tup1, f) #用 dump 函数将 Python 对象转成二进制对象文件

In [11]:
import torch
import torch.nn.functional as F

In [10]:
F.softmax(torch.arange(10).reshape(2, 5).float(),dim=1)

tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])

In [19]:
torch.mean(torch.arange(10).reshape(2, 5).float(), dim=-1,keepdim=True).shape

torch.Size([2, 1])

In [25]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.stack([a, b], 1).shape

torch.Size([3, 2])

In [6]:
(103 * 91 + 80 * 3 )/106

90.68867924528301